version: '3.7'

services:

  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgre
    volumes:
      - postgres-data:/var/lib/postgresql/data

  application:
    image: "asayke/jwtapp:1.5.7"
    container_name: application
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_PASSWORD=postgre
      - DATASOURCE_URL=jdbc:postgresql://database:5432/jwtappbase
      - DATASOURCE_USERNAME=postgres
      - JWT_EXPIRED=1000000
      - JWT_SECRET=amogus

volumes:
  postgres-data: